# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
