# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='User', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.CharField(default='My Bio', max_length=1000),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
