# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20171012_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
