# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_events_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
