# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20171014_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='hometown',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schedules',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='city_schedules', to='profiles.city'),
        ),
    ]
