# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20171016_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_schedules', to='profiles.city'),
        ),
    ]
