# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20171016_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='city',
            new_name='mycity',
        ),
    ]
