# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_remove_schedules_mycity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
