# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_delete_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='person_likes',
        ),
        migrations.AlterField(
            model_name='person',
            name='hometown',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.person'),
        ),
    ]
